// Copyright (c) 2026 Alexander Penkin. MIT License.

#include "Utils/AssetDumpWriter.h"
#include "Utils/UnifiedDiff.h"
#include "Compat/EngineVersionCompat.h"
#include "PinWrightProjectSettings.h"
#include "PinWrightSubsystem.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace AssetDumpWriter
{

FString ResolveDumpRoot(const FString& OutRoot)
{
    // Per-call outRoot override wins; then the project-settings override;
    // then the default under the project's Saved folder.
    FString Root = OutRoot;
    if (Root.IsEmpty())
    {
        Root = GetDefault<UPinWrightProjectSettings>()->AssetDumpRootDirectory;
    }
    if (Root.IsEmpty())
    {
        Root = FPaths::ProjectSavedDir() / TEXT("PinWright") / TEXT("asset-dumps");
    }
    else if (FPaths::IsRelative(Root))
    {
        // Relative roots — explicit outRoot or the project setting — resolve
        // against the project dir, never the process CWD: the editor's CWD is
        // the engine Binaries folder, so CWD-relative roots silently dump into
        // the engine installation. The project dir is made absolute BEFORE the
        // join: where the project lives outside the engine tree, ProjectDir()
        // is itself a "../../../.." path relative to the executable's BaseDir,
        // and joining onto that form makes the resolved root depend on where
        // the process was started from.
        Root = FPaths::ConvertRelativePathToFull(FPaths::ProjectDir()) / Root;
    }
    FPaths::NormalizeDirectoryName(Root);
    return FPaths::ConvertRelativePathToFull(Root);
}

FString ResolveDumpDir(const FString& PackagePath, const FString& OutRoot)
{
    FString Root = ResolveDumpRoot(OutRoot);

    // Strip leading '/' so joining produces "Root/Game/..." not "Root//Game/..."
    FString Relative = PackagePath;
    if (Relative.StartsWith(TEXT("/"))) Relative.RemoveAt(0, 1);

    FString Combined = Root / Relative;
    FPaths::NormalizeFilename(Combined);
    return FPaths::ConvertRelativePathToFull(Combined);
}

FString ResolveDiffRoot()
{
    // Diff artifacts always live under the project's Saved folder — never under
    // the baseline mirror, which may be committed to git in host projects.
    FString Root = FPaths::ProjectSavedDir() / TEXT("PinWright") / TEXT("asset-dump-diffs");
    FPaths::NormalizeDirectoryName(Root);
    return FPaths::ConvertRelativePathToFull(Root);
}

FString ResolveDiffDir(const FString& PackagePath)
{
    FString Root = ResolveDiffRoot();

    // Strip leading '/' so joining produces "Root/Game/..." not "Root//Game/..."
    FString Relative = PackagePath;
    if (Relative.StartsWith(TEXT("/"))) Relative.RemoveAt(0, 1);

    FString Combined = Root / Relative;
    FPaths::NormalizeFilename(Combined);
    return FPaths::ConvertRelativePathToFull(Combined);
}

void FindOwnDumpFiles(const FString& DumpDir, TArray<FString>& OutFiles)
{
    IFileManager& FM = IFileManager::Get();
    FString Root = FPaths::ConvertRelativePathToFull(DumpDir);
    FPaths::NormalizeDirectoryName(Root);
    TArray<FString> PendingDirs{Root};
    while (PendingDirs.Num() > 0)
    {
        const FString Dir = PendingDirs.Pop();
        FM.IterateDirectory(*Dir, [&](const TCHAR* Path, bool bIsDirectory)
        {
            FString FullPath = FPaths::ConvertRelativePathToFull(Path);
            FPaths::NormalizeFilename(FullPath);
            if (!bIsDirectory)
            {
                OutFiles.Add(MoveTemp(FullPath));
            }
            else if (!FM.FileExists(*(FullPath / TEXT("meta.json")))
                && !FM.FileExists(*(FullPath / TEXT(".dumpcache.json"))))
            {
                PendingDirs.Add(MoveTemp(FullPath));
            }
            return true;
        });
    }
}

bool CheckPathLength(const FString& AbsDir, FString& OutError)
{
    if (AbsDir.Len() > 260)
    {
        OutError = FString::Printf(TEXT("Path exceeds MAX_PATH (260): %s"), *AbsDir);
        return false;
    }
    return true;
}

void EnsureDumpRootScaffold(const FString& DumpRoot)
{
    FString AbsRoot = FPaths::ConvertRelativePathToFull(DumpRoot);
    FPaths::NormalizeDirectoryName(AbsRoot);

    IFileManager::Get().MakeDirectory(*AbsRoot, /*Tree=*/true);

    // Shared by CLAUDE.md and AGENTS.md so both agent ecosystems get identical orientation.
    static const TCHAR* AgentOrientationMd =
        TEXT("# PinWright asset-dump cache\n")
        TEXT("\n")
        TEXT("Auto-generated by the PinWright `asset.dump` / `asset.dump_folder` RPCs. Never hand-edit dump files - edits are lost on the next sweep. One folder per asset, mirroring its UE package path; the sidecar set varies by asset type. Skip stubs carry only `meta.json` with `\"skipped\": true` - branch on that before opening other sidecars.\n")
        TEXT("\n")
        TEXT("- **Staleness:** dumps reflect asset state at the last sweep. If a file looks outdated or is missing, fall back to a live `asset.dump` MCP call and re-run `asset.dump_folder` for that subtree.\n")
        TEXT("- **Refresh:** `asset.dump` with `force=true` for one asset; `asset.dump_folder` for a subtree. The per-asset `.dumpcache.json` (gitignored) makes unchanged assets no-ops.\n")
        TEXT("- **Git:** this tree is derived data. Never hand-resolve merge conflicts - take either side wholesale (e.g. `git merge -X theirs`) and re-run the sweep to restore truth. Diffs between sweeps are meaningful; conflicts are not.\n")
        TEXT("- `.gitignore`, `.gitattributes`, `CLAUDE.md`, and `AGENTS.md` (identical content) are seeded create-if-missing by the dumper; delete one to regenerate the default.\n");

    struct FScaffoldFile
    {
        const TCHAR* Name;
        const TCHAR* Content;
    };
    static const FScaffoldFile ScaffoldFiles[] =
    {
        { TEXT(".gitignore"),
          TEXT("# PinWright dump-cache bookkeeping (engine/plugin versions, package hashes) - transient, never commit.\n")
          TEXT(".dumpcache.json\n")
          TEXT("*.tmp\n") },
        { TEXT(".gitattributes"),
          TEXT("# Machine-generated dump tree: bytes on disk are canonical; never normalize line endings.\n")
          TEXT("* -text\n") },
        { TEXT("CLAUDE.md"), AgentOrientationMd },
        { TEXT("AGENTS.md"), AgentOrientationMd },
    };

    for (const FScaffoldFile& File : ScaffoldFiles)
    {
        FString Path = AbsRoot / File.Name;
        if (FPaths::FileExists(Path))
        {
            continue; // Create-if-missing: never overwrite user customizations.
        }

        bool bSaved = FFileHelper::SaveStringToFile(
            File.Content, *Path,
            FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
        if (!bSaved)
        {
            // Non-fatal: the dump itself matters more than the git scaffold.
            UE_LOG(LogPinWrightSubsystem, Warning,
                TEXT("EnsureDumpRootScaffold: failed to write %s"), *Path);
        }
    }
}

FWriteResult WriteAssetDump(const FString& DumpDir, const FString& DumpRoot,
                            const TArray<FDumpFile>& Files, FString& OutError)
{
    const TMap<FString, TArray<uint8>> NoBinaryFiles;
    return WriteAssetDump(DumpDir, DumpRoot, Files, NoBinaryFiles, OutError);
}


namespace
{

bool IsSafeRelativeDumpName(const FString& Name)
{
    if (Name.IsEmpty()
        || Name.Contains(TEXT(":"))
        || Name.StartsWith(TEXT("/"))
        || Name.StartsWith(TEXT("\\"))
        || Name.Contains(TEXT("..")))
    {
        return false;
    }
    return true;
}

bool TryResolveDumpFilePath(const FString& AbsDir, const FString& Name, FString& OutPath)
{
    if (!IsSafeRelativeDumpName(Name))
    {
        return false;
    }

    OutPath = FPaths::ConvertRelativePathToFull(AbsDir / Name);
    FPaths::NormalizeFilename(OutPath);
    return OutPath.StartsWith(AbsDir + TEXT("/"));
}

FString MakeDumpPathKey(const FString& Path)
{
    FString Key = Path;
    FPaths::NormalizeFilename(Key);
#if PLATFORM_WINDOWS
    Key.ToLowerInline();
#endif
    return Key;
}

TArray<uint8> EncodeUtf8(const FString& Content)
{
    FTCHARToUTF8 Converted(*Content, Content.Len());
    TArray<uint8> Bytes;
    Bytes.Append(reinterpret_cast<const uint8*>(Converted.Get()), Converted.Length());
    return Bytes;
}

FString StripTrailingLineWhitespace(const FString& Content)
{
    FString Result;
    Result.Reserve(Content.Len());
    for (const TCHAR Character : Content)
    {
        if (Character == TEXT('\r') || Character == TEXT('\n'))
        {
            while (!Result.IsEmpty()
                && (Result[Result.Len() - 1] == TEXT(' ')
                    || Result[Result.Len() - 1] == TEXT('\t')))
            {
                Result.LeftChopInline(1, EAllowShrinking::No);
            }
        }
        Result.AppendChar(Character);
    }
    while (!Result.IsEmpty()
        && (Result[Result.Len() - 1] == TEXT(' ')
            || Result[Result.Len() - 1] == TEXT('\t')))
    {
        Result.LeftChopInline(1, EAllowShrinking::No);
    }
    return Result;
}

struct FPreparedDumpFile
{
    FString Name;
    FString FinalPath;
    FString StagedPath;
    FString BackupPath;
    TArray<uint8> Bytes;
    bool bChanged = false;
    bool bHadPrevious = false;
};

struct FMovedStaleFile
{
    FString OriginalPath;
    FString BackupPath;
};

void AddWriteError(
    FWriteResult& Result,
    const FString& Name,
    const FString& Message,
    FString& OutError)
{
    Result.Errors.Add(TPair<FString, FString>(Name, Message));
    if (OutError.IsEmpty())
    {
        OutError = Message;
    }
}

void CleanupTransactionDirectory(const FString& Path)
{
    if (!Path.IsEmpty()
        && IFileManager::Get().DirectoryExists(*Path)
        && !IFileManager::Get().DeleteDirectory(*Path, /*RequireExists=*/false, /*Tree=*/true))
    {
        UE_LOG(LogPinWrightSubsystem, Warning,
            TEXT("Asset dump writer could not remove transaction directory: %s"), *Path);
    }
}

bool TryMakeRelativeSiblingPath(
    const FString& AbsDir,
    const FString& Name,
    const FString& Suffix,
    const FString& Extension,
    FString& OutPath)
{
    if (!IsSafeRelativeDumpName(Name))
    {
        return false;
    }

    const FString RelativeDir = FPaths::GetPath(Name);
    const FString Stem = FPaths::GetBaseFilename(Name, /*bRemovePath=*/true);
    const FString FileName = Stem + Suffix + Extension;
    OutPath = RelativeDir.IsEmpty() ? AbsDir / FileName : AbsDir / RelativeDir / FileName;
    OutPath = FPaths::ConvertRelativePathToFull(OutPath);
    FPaths::NormalizeFilename(OutPath);
    return OutPath.StartsWith(AbsDir + TEXT("/"));
}

bool WriteFileAtomic(const FString& FinalPath, const FString& Content,
                     TArray<FString>& WrittenPaths,
                     TArray<TPair<FString, FString>>& Errors,
                     const FString& Name)
{
    IFileManager& FM = IFileManager::Get();
    FM.MakeDirectory(*FPaths::GetPath(FinalPath), /*Tree=*/true);
    FString TmpPath = FinalPath + TEXT(".tmp");

    bool bSaved = FFileHelper::SaveStringToFile(
        StripTrailingLineWhitespace(Content), *TmpPath,
        FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
    if (!bSaved)
    {
        FM.Delete(*TmpPath, /*RequireExists=*/false);
        Errors.Add(TPair<FString, FString>(Name,
            FString::Printf(TEXT("Failed to write tmp file: %s"), *TmpPath)));
        return false;
    }

    bool bMoved = FM.Move(*FinalPath, *TmpPath, /*bReplace=*/true, /*bEvenReadOnly=*/false);
    if (!bMoved)
    {
        FM.Delete(*TmpPath, /*RequireExists=*/false);
        Errors.Add(TPair<FString, FString>(Name,
            FString::Printf(TEXT("Failed to rename tmp to final: %s"), *FinalPath)));
        return false;
    }

    WrittenPaths.Add(FinalPath);
    return true;
}

} // anonymous namespace

FWriteResult WriteAssetDump(
    const FString& DumpDir,
    const FString& DumpRoot,
    const TArray<FDumpFile>& Files,
    const TMap<FString, TArray<uint8>>& BinaryFiles,
    FString& OutError)
{
    FWriteResult Result;
    OutError.Reset();

    FString AbsDir = FPaths::ConvertRelativePathToFull(DumpDir);
    FString AbsRoot = FPaths::ConvertRelativePathToFull(DumpRoot);
    FPaths::NormalizeDirectoryName(AbsDir);
    FPaths::NormalizeDirectoryName(AbsRoot);

    if (!AbsDir.StartsWith(AbsRoot + TEXT("/")))
    {
        OutError = FString::Printf(
            TEXT("DumpDir is not a strict subpath of DumpRoot. DumpDir=%s DumpRoot=%s"),
            *DumpDir, *DumpRoot);
        return Result;
    }

    EnsureDumpRootScaffold(AbsRoot);

    TArray<FPreparedDumpFile> Prepared;
    Prepared.Reserve(Files.Num() + BinaryFiles.Num());
    TSet<FString> SeenPaths;

    auto AddPrepared = [&](const FString& Name, TArray<uint8>&& Bytes) -> bool
    {
        FString NormalizedName = Name;
        FPaths::NormalizeFilename(NormalizedName);

        FString FinalPath;
        if (!TryResolveDumpFilePath(AbsDir, NormalizedName, FinalPath))
        {
            AddWriteError(Result, Name,
                FString::Printf(TEXT("Unsafe relative dump file name: %s"), *Name), OutError);
            return false;
        }
        const FString PathKey = MakeDumpPathKey(FinalPath);
        if (SeenPaths.Contains(PathKey))
        {
            AddWriteError(Result, Name,
                FString::Printf(TEXT("Duplicate dump file name: %s"), *Name), OutError);
            return false;
        }

        SeenPaths.Add(PathKey);
        FPreparedDumpFile& Entry = Prepared.AddDefaulted_GetRef();
        Entry.Name = MoveTemp(NormalizedName);
        Entry.FinalPath = MoveTemp(FinalPath);
        Entry.Bytes = MoveTemp(Bytes);
        return true;
    };

    for (const FDumpFile& File : Files)
    {
        if (!AddPrepared(File.Name, EncodeUtf8(StripTrailingLineWhitespace(File.Content))))
        {
            return Result;
        }
    }
    for (const TPair<FString, TArray<uint8>>& Binary : BinaryFiles)
    {
        TArray<uint8> Bytes = Binary.Value;
        if (!AddPrepared(Binary.Key, MoveTemp(Bytes)))
        {
            return Result;
        }
    }

    Prepared.Sort([](const FPreparedDumpFile& A, const FPreparedDumpFile& B)
    {
        return A.Name < B.Name;
    });

    // Reject file/directory collisions before staging. Checking every ancestor
    // avoids relying on conflicting paths being adjacent in lexical order.
    for (const FPreparedDumpFile& Entry : Prepared)
    {
        FString AncestorPath = FPaths::GetPath(Entry.FinalPath);
        while (AncestorPath.Len() > AbsDir.Len())
        {
            if (SeenPaths.Contains(MakeDumpPathKey(AncestorPath)))
            {
                AddWriteError(Result, Entry.Name,
                    FString::Printf(TEXT("Dump file path conflicts with another file: %s"),
                        *Entry.Name), OutError);
                return Result;
            }

            const FString ParentPath = FPaths::GetPath(AncestorPath);
            if (ParentPath == AncestorPath)
            {
                break;
            }
            AncestorPath = ParentPath;
        }
    }

    IFileManager& FM = IFileManager::Get();
    for (FPreparedDumpFile& Entry : Prepared)
    {
        if (FM.DirectoryExists(*Entry.FinalPath))
        {
            AddWriteError(Result, Entry.Name,
                FString::Printf(TEXT("Dump file destination is a directory: %s"), *Entry.FinalPath),
                OutError);
            return Result;
        }

        if (FM.FileExists(*Entry.FinalPath))
        {
            TArray<uint8> ExistingBytes;
            if (!FFileHelper::LoadFileToArray(ExistingBytes, *Entry.FinalPath))
            {
                AddWriteError(Result, Entry.Name,
                    FString::Printf(TEXT("Failed to read existing dump file: %s"), *Entry.FinalPath),
                    OutError);
                return Result;
            }
            Entry.bChanged = ExistingBytes != Entry.Bytes;
        }
        else
        {
            Entry.bChanged = true;
        }
    }

    const FString TransactionId = FGuid::NewGuid().ToString(EGuidFormats::Digits);
    const FString StageRoot = AbsDir + TEXT(".tmp-") + TransactionId;
    const FString BackupRoot = AbsDir + TEXT(".bak-") + TransactionId;

    // Prepare every changed byte sequence before replacing anything in the mirror.
    for (FPreparedDumpFile& Entry : Prepared)
    {
        if (!Entry.bChanged)
        {
            continue;
        }

        Entry.StagedPath = StageRoot / Entry.Name;
        if (!FM.MakeDirectory(*FPaths::GetPath(Entry.StagedPath), /*Tree=*/true)
            || !FFileHelper::SaveArrayToFile(
                TArrayView64<const uint8>(Entry.Bytes.GetData(), Entry.Bytes.Num()),
                *Entry.StagedPath))
        {
            AddWriteError(Result, Entry.Name,
                FString::Printf(TEXT("Failed to stage dump file: %s"), *Entry.StagedPath), OutError);
            CleanupTransactionDirectory(StageRoot);
            CleanupTransactionDirectory(BackupRoot);
            return Result;
        }
    }

    TArray<FPreparedDumpFile*> Committed;
    TArray<FMovedStaleFile> MovedStale;

    auto RollBack = [&]()
    {
        bool bRestoreSucceeded = true;
        for (int32 Index = MovedStale.Num() - 1; Index >= 0; --Index)
        {
            const FMovedStaleFile& Stale = MovedStale[Index];
            if (!FM.MakeDirectory(*FPaths::GetPath(Stale.OriginalPath), /*Tree=*/true)
                || !FM.Move(*Stale.OriginalPath, *Stale.BackupPath,
                    /*bReplace=*/true, /*bEvenReadOnly=*/false))
            {
                bRestoreSucceeded = false;
                Result.Errors.Add(TPair<FString, FString>(Stale.OriginalPath,
                    TEXT("Rollback failed to restore stale file")));
            }
        }

        for (int32 Index = Committed.Num() - 1; Index >= 0; --Index)
        {
            FPreparedDumpFile* Entry = Committed[Index];
            if (FM.FileExists(*Entry->FinalPath)
                && !FM.Delete(*Entry->FinalPath,
                    /*RequireExists=*/false, /*EvenReadOnly=*/false))
            {
                bRestoreSucceeded = false;
                Result.Errors.Add(TPair<FString, FString>(Entry->Name,
                    TEXT("Rollback failed to remove newly committed dump file")));
            }
            if (Entry->bHadPrevious)
            {
                if (!FM.MakeDirectory(*FPaths::GetPath(Entry->FinalPath), /*Tree=*/true)
                    || !FM.Move(*Entry->FinalPath, *Entry->BackupPath,
                        /*bReplace=*/true, /*bEvenReadOnly=*/false))
                {
                    bRestoreSucceeded = false;
                    Result.Errors.Add(TPair<FString, FString>(Entry->Name,
                        TEXT("Rollback failed to restore previous dump file")));
                }
            }
        }

        CleanupTransactionDirectory(StageRoot);
        if (bRestoreSucceeded)
        {
            CleanupTransactionDirectory(BackupRoot);
        }
        else
        {
            const FString RecoveryMessage = FString::Printf(
                TEXT("Rollback was incomplete; recovery files were preserved at: %s"),
                *BackupRoot);
            Result.Errors.Add(TPair<FString, FString>(TEXT("rollback"), RecoveryMessage));
            OutError += FString::Printf(TEXT(" %s"), *RecoveryMessage);
        }
    };

    for (FPreparedDumpFile& Entry : Prepared)
    {
        if (!Entry.bChanged)
        {
            continue;
        }

        Entry.bHadPrevious = FM.FileExists(*Entry.FinalPath);
        Entry.BackupPath = BackupRoot / TEXT("changed") / Entry.Name;
        if (Entry.bHadPrevious)
        {
            if (!FM.MakeDirectory(*FPaths::GetPath(Entry.BackupPath), /*Tree=*/true)
                || !FM.Move(*Entry.BackupPath, *Entry.FinalPath,
                    /*bReplace=*/false, /*bEvenReadOnly=*/false))
            {
                AddWriteError(Result, Entry.Name,
                    FString::Printf(TEXT("Failed to back up existing dump file: %s"),
                        *Entry.FinalPath), OutError);
                RollBack();
                return Result;
            }
        }

        Committed.Add(&Entry);
        if (!FM.MakeDirectory(*FPaths::GetPath(Entry.FinalPath), /*Tree=*/true)
            || !FM.Move(*Entry.FinalPath, *Entry.StagedPath,
                /*bReplace=*/false, /*bEvenReadOnly=*/false))
        {
            AddWriteError(Result, Entry.Name,
                FString::Printf(TEXT("Failed to commit staged dump file: %s"), *Entry.FinalPath),
                OutError);
            RollBack();
            return Result;
        }
    }

    TSet<FString> IntendedPathKeys;
    for (const FPreparedDumpFile& Entry : Prepared)
    {
        IntendedPathKeys.Add(MakeDumpPathKey(Entry.FinalPath));
    }

    // Only this asset's files: a nested dump dir belongs to another asset (asset /P/X
    // beside folder /P/X/) and its sidecars must survive this prune.
    TArray<FString> ExistingFiles;
    FindOwnDumpFiles(AbsDir, ExistingFiles);
    ExistingFiles.Sort();
    for (const FString& ExistingPath : ExistingFiles)
    {
        FString NormalizedPath = FPaths::ConvertRelativePathToFull(ExistingPath);
        FPaths::NormalizeFilename(NormalizedPath);
        if (IntendedPathKeys.Contains(MakeDumpPathKey(NormalizedPath))
            || FPaths::GetCleanFilename(NormalizedPath) == TEXT(".dumpcache.json"))
        {
            continue;
        }

        FString RelativePath = NormalizedPath;
        FPaths::MakePathRelativeTo(RelativePath, *(AbsDir + TEXT("/")));
        FPaths::NormalizeFilename(RelativePath);
        const FString BackupPath = BackupRoot / TEXT("stale") / RelativePath;
        if (!FM.MakeDirectory(*FPaths::GetPath(BackupPath), /*Tree=*/true)
            || !FM.Move(*BackupPath, *NormalizedPath,
                /*bReplace=*/false, /*bEvenReadOnly=*/false))
        {
            AddWriteError(Result, RelativePath,
                FString::Printf(TEXT("Failed to prune stale dump file: %s"), *NormalizedPath),
                OutError);
            RollBack();
            return Result;
        }
        MovedStale.Add({NormalizedPath, BackupPath});
    }

    // Delete now-empty stale directories, deepest first. Expected directories
    // containing an intended file remain non-empty and are therefore untouched.
    TArray<FString> ExistingDirectories;
    FM.FindFilesRecursive(ExistingDirectories, *AbsDir, TEXT("*"), /*Files=*/false,
        /*Directories=*/true, /*bClearFileNames=*/true);
    ExistingDirectories.Sort([](const FString& A, const FString& B)
    {
        return A.Len() > B.Len();
    });
    for (const FString& Directory : ExistingDirectories)
    {
        FM.DeleteDirectory(*Directory, /*RequireExists=*/false, /*Tree=*/false);
    }

    CleanupTransactionDirectory(StageRoot);
    CleanupTransactionDirectory(BackupRoot);

    // WrittenPaths means the complete successful baseline sidecar set, not only
    // physically changed files. AssetDumpCache fingerprints this list.
    for (const FPreparedDumpFile& Entry : Prepared)
    {
        Result.WrittenPaths.Add(Entry.FinalPath);
    }
    return Result;
}

bool WriteAssetDumpBinaryFile(
    const FString& AbsDumpDir,
    const FString& RelName,
    TArrayView<const uint8> Bytes,
    FString& OutAbsPath,
    FString& OutError)
{
    OutAbsPath.Reset();
    OutError.Reset();

    if (!IsSafeRelativeDumpName(RelName))
    {
        OutError = FString::Printf(TEXT("Unsafe relative dump file name: %s"), *RelName);
        return false;
    }

    FString AbsDir = FPaths::ConvertRelativePathToFull(AbsDumpDir);
    FPaths::NormalizeDirectoryName(AbsDir);

    FString FinalPath = AbsDir / RelName;
    FPaths::NormalizeFilename(FinalPath);
    FinalPath = FPaths::ConvertRelativePathToFull(FinalPath);
    if (!FinalPath.StartsWith(AbsDir + TEXT("/")))
    {
        OutError = FString::Printf(TEXT("Resolved path escapes dump dir: %s"), *FinalPath);
        return false;
    }

    IFileManager& FM = IFileManager::Get();
    if (FM.FileExists(*FinalPath))
    {
        TArray<uint8> ExistingBytes;
        if (!FFileHelper::LoadFileToArray(ExistingBytes, *FinalPath))
        {
            OutError = FString::Printf(TEXT("Failed to read existing binary dump file: %s"),
                *FinalPath);
            return false;
        }
        if (ExistingBytes.Num() == Bytes.Num()
            && (Bytes.Num() == 0
                || FMemory::Memcmp(ExistingBytes.GetData(), Bytes.GetData(), Bytes.Num()) == 0))
        {
            OutAbsPath = FinalPath;
            return true;
        }
    }

    if (!FM.MakeDirectory(*FPaths::GetPath(FinalPath), /*Tree=*/true))
    {
        OutError = FString::Printf(TEXT("Failed to create binary dump directory: %s"),
            *FPaths::GetPath(FinalPath));
        return false;
    }

    const FString TmpPath = FinalPath + TEXT(".tmp");
    if (!FFileHelper::SaveArrayToFile(
            TArrayView64<const uint8>(Bytes.GetData(), Bytes.Num()), *TmpPath))
    {
        FM.Delete(*TmpPath, /*RequireExists=*/false);
        OutError = FString::Printf(TEXT("Failed to write tmp file: %s"), *TmpPath);
        return false;
    }

    const FString BackupPath = FinalPath + TEXT(".bak-")
        + FGuid::NewGuid().ToString(EGuidFormats::Digits);
    const bool bHadPrevious = FM.FileExists(*FinalPath);
    if (bHadPrevious)
    {
        FM.Delete(*BackupPath, /*RequireExists=*/false, /*EvenReadOnly=*/false);
        if (!FM.Move(*BackupPath, *FinalPath,
                /*bReplace=*/false, /*bEvenReadOnly=*/false))
        {
            FM.Delete(*TmpPath, /*RequireExists=*/false);
            OutError = FString::Printf(TEXT("Failed to back up binary dump file: %s"), *FinalPath);
            return false;
        }
    }

    if (!FM.Move(*FinalPath, *TmpPath, /*bReplace=*/false, /*bEvenReadOnly=*/false))
    {
        FM.Delete(*TmpPath, /*RequireExists=*/false);
        const FString CommitError = FString::Printf(
            TEXT("Failed to rename tmp to final: %s"), *FinalPath);
        if (bHadPrevious)
        {
            if (!FM.Move(*FinalPath, *BackupPath,
                    /*bReplace=*/true, /*bEvenReadOnly=*/false))
            {
                OutError = FString::Printf(
                    TEXT("%s Rollback failed; previous bytes were preserved at: %s"),
                    *CommitError,
                    *BackupPath);
                return false;
            }
        }
        OutError = CommitError;
        return false;
    }

    FM.Delete(*BackupPath, /*RequireExists=*/false, /*EvenReadOnly=*/false);

    OutAbsPath = FinalPath;
    return true;
}

// Callers pass the DIFF output dir/root (ResolveDiffDir/ResolveDiffRoot in
// production; scratch dirs in unit tests), never the baseline mirror.
FWriteResult WriteAssetDumpDiff(
    const FString& DumpDir,
    const FString& DumpRoot,
    const FString& LatestMetaJson,
    const TArray<FBaselineDumpFile>& Aspects,
    FString& OutError)
{
    FWriteResult Result;

    // Absolutize both paths so WrittenPaths are absolute and the subpath guard
    // compares like-for-like regardless of how the caller passed them in.
    FString AbsDir  = FPaths::ConvertRelativePathToFull(DumpDir);
    FString AbsRoot = FPaths::ConvertRelativePathToFull(DumpRoot);
    FPaths::NormalizeDirectoryName(AbsDir);
    FPaths::NormalizeDirectoryName(AbsRoot);

    if (!AbsDir.StartsWith(AbsRoot + TEXT("/")))
    {
        OutError = FString::Printf(
            TEXT("DumpDir is not a strict subpath of DumpRoot. DumpDir=%s DumpRoot=%s"),
            *DumpDir, *DumpRoot);
        return Result;
    }

    // Wipe + recreate so each diff run fully replaces the previous one's artifacts.
    // No scaffold seeding here: diff artifacts live under Saved/, never in the
    // committed mirror (see ResolveDiffRoot).
    IFileManager& FM = IFileManager::Get();
    FM.DeleteDirectory(*AbsDir, /*RequireExists=*/false, /*Tree=*/true);
    FM.MakeDirectory(*AbsDir, /*Tree=*/true);

    // Always rewrite meta.json.
    WriteFileAtomic(AbsDir / TEXT("meta.json"), LatestMetaJson,
        Result.WrittenPaths, Result.Errors, TEXT("meta.json"));

    for (const FBaselineDumpFile& Aspect : Aspects)
    {
        // Compare the exact canonical text that normal and diff writes emit. Otherwise a
        // generated trailing space that the writer removes looks like a real asset change.
        const FString OldContent = StripTrailingLineWhitespace(Aspect.OldContent);
        const FString NewContent = StripTrailingLineWhitespace(Aspect.NewContent);
        if (OldContent == NewContent)
            continue;

        FString Ext = FPaths::GetExtension(Aspect.Name, /*bIncludeDot=*/true);

        if (!NewContent.IsEmpty())
        {
            FString NewPath;
            if (TryMakeRelativeSiblingPath(AbsDir, Aspect.Name, TEXT("_new"), Ext, NewPath))
            {
                WriteFileAtomic(NewPath, NewContent,
                    Result.WrittenPaths, Result.Errors, Aspect.Name + TEXT("_new"));
            }
            else
            {
                Result.Errors.Add(TPair<FString, FString>(Aspect.Name,
                    TEXT("Unsafe diff aspect path")));
            }
        }

        FString DiffContent = UnifiedDiff::MakeUnifiedDiff(
            OldContent, NewContent,
            Aspect.Name, Aspect.Name + TEXT(" (new)"));
        FString DiffPath;
        if (TryMakeRelativeSiblingPath(AbsDir, Aspect.Name, TEXT("_diff"), TEXT(".txt"), DiffPath))
        {
            WriteFileAtomic(DiffPath, DiffContent,
                Result.WrittenPaths, Result.Errors, Aspect.Name + TEXT("_diff"));
        }
        else
        {
            Result.Errors.Add(TPair<FString, FString>(Aspect.Name,
                TEXT("Unsafe diff aspect path")));
        }
    }

    return Result;
}

} // namespace AssetDumpWriter
