// Copyright (c) 2026 Alexander Penkin. MIT License.

// PwSourceAssetUserData.h - provenance for assets generated by source formats other than
// .pwmodel.  UPwModelAssetUserData remains in PinWrightGeometry deliberately: changing its
// reflected class path would orphan stamps already serialized onto existing UStaticMesh assets.
#pragma once

#include "CoreMinimal.h"
#include "Engine/AssetUserData.h"

#include "PwSourceAssetUserData.generated.h"

// Provenance shared by the main-module source formats (.pwskel and .pwanim).
//
// This is a separate reflected class from UPwModelAssetUserData.  Reusing the model class by
// moving it into this module would change its UCLASS path and make already-generated .pwmodel
// assets lose the stamp that permits a same-source recompile without overwrite=true.
UCLASS()
class PINWRIGHT_API UPwSourceAssetUserData : public UAssetUserData
{
    GENERATED_BODY()

public:
    // Project-relative when the source is under the project; absolute otherwise.  The producer
    // owns that normalization so the same source has the same value on the next compile.
    UPROPERTY()
    FString SourcePath;

    // Recorded for provenance and future tooling.  It is not an overwrite permission check:
    // changing the source is the normal iteration path.
    UPROPERTY()
    FString SourceHash;

    // Versioned semantic state written by the source compiler after a successful build. On the
    // next compile it is compared with both the live asset and the new source. That three-way
    // comparison distinguishes an ordinary source edit from an edit made directly to the asset.
    UPROPERTY()
    int32 GeneratedStateVersion = 0;

    UPROPERTY()
    TMap<FString, FString> GeneratedState;
};
