// Copyright (c) 2026 Alexander Penkin. MIT License.

// Tests for PwRenderMetaSoundSource - the offline MetaSound -> PCM path behind
// audio.synth.render_metasound (board ticket F-metasound-no-render-to-pcm).
//
// The fixture is an in-memory MetaSound built through the engine's own
// UMetaSoundBuilderSubsystem: a Mono, non-one-shot Source whose UE.Sine oscillator is wired
// to the audio output and whose Frequency pin is fed from a Float graph input. Nothing is
// written to disk and no project content is referenced, so the tests are host-independent
// (CLAUDE.md > "This plugin is the deliverable, and it is general-purpose").
//
// Non-one-shot is deliberate: a one-shot Source built this way carries an OnFinished output
// with nothing driving it usefully, and any early finish would make "did it produce audio"
// unmeasurable. RendersNonSilentBuffer pins that choice from both sides - with
// bIsOneShot=false the render must report finished:false AND truncated:true, so a fixture that
// silently became one-shot fails there rather than quietly shortening every other test.

#include "Misc/AutomationTest.h"

#include "AudioGen/PwMetaSoundRender.h"

#if PW_HAS_METASOUND_RENDER

#include "AudioGen/PwAudioAnalysis.h"
#include "AudioGen/PwAudioBuffer.h"
#include "Compat/EngineVersionCompat.h"
#include "Handlers/ErrorCodes.h"
#include "Tests/TestSkipReporting.h"

// FThreadSafeCounter (the fixture serial) and FGuid are NOT in CoreMinimal.h - included
// explicitly so this file does not depend on another header dragging them in.
#include "Engine/Engine.h"
#include "HAL/ThreadSafeCounter.h"
#include "Misc/Guid.h"

// UMetaSoundBuilderBase was split out of MetasoundBuilderSubsystem.h into its own header in
// UE 5.5; through 5.4 the subsystem header declares it and MetasoundBuilderBase.h does not exist.
#if UE_VERSION_NEWER_THAN_OR_EQUAL(5, 5, 0)
#include "MetasoundBuilderBase.h"
#endif
#include "MetasoundBuilderSubsystem.h"
#include "MetasoundDocumentInterface.h"
#include "MetasoundFrontendDocument.h"
#include "MetasoundFrontendLiteral.h"
#include "MetasoundSource.h"

// Named (not anonymous) namespace: the main module builds with Unity on, and two anonymous
// namespaces merged into one TU collide by name. See CLAUDE.md > Building.
namespace PwMetaSoundRenderTestFixture
{
    /** Default the fixture's graph input carries when nothing overrides it. */
    constexpr float DefaultFrequencyHz = 220.0f;

    /** Sine node identity, from MetasoundOscillatorNodes.cpp:308 - {StandardNodes::Namespace,
     *  "Sine", StandardNodes::AudioVariant}, i.e. UE / Sine / Audio, major version 1.
     *  Built on first call, never at static-init time: FName construction before the name
     *  table is up is undefined. */
    const FMetasoundFrontendClassName& SineClassName()
    {
        static const FMetasoundFrontendClassName Name(FName("UE"), FName("Sine"), FName("Audio"));
        return Name;
    }

    /**
     * THE BUILDER AND THE ASSET IT BUILDS MUST NOT SHARE A BASE NAME. This is not tidiness -
     * passing one name for both is a FATAL, and it fired here (UObjectGlobals.cpp:3533,
     * "Cannot replace existing object of a different class ...
     * MetaSoundSource /Engine/Transient.PwRenderFixture_<guid>_0 vs
     * MetaSoundSourceBuilder /Engine/Transient.PwRenderFixture_<guid>_0").
     *
     * The two names are generated by two DIFFERENT branches of MakeUniqueObjectName, and only
     * one of them checks the transient package:
     *
     *   builder - CreateTransientBuilder passes Parent = GetTransientPackage()
     *             (MetasoundDocumentBuilderRegistry.h:50), so the editor branch takes
     *             UpdateSuffixForNextNewObject, which is keyed per (Parent, base name) and
     *             starts at 0 for a base name that package has not seen. Fresh GUID base ->
     *             always "_0".
     *   asset   - BuildInternal calls MakeUniqueObjectName(Parent, ...) while Parent is still
     *             nullptr and only assigns GetTransientPackage() on the NEXT line
     *             (MetasoundBuilderBase.h:671-679). With a null Parent the suffix comes from
     *             the global monotonic UMetaSoundSource::ClassUnique, and the collision probe
     *             degrades to StaticFindObjectFastInternal(nullptr, nullptr, TestName), which
     *             searches outer-less objects and therefore cannot see anything inside
     *             /Engine/Transient. The suffix is never checked against the builder.
     *
     * FName stores its number +1, so the first ClassUnique increment renders as "_0" too - which
     * makes the crash DETERMINISTIC on the first fixture built in a process that has not yet
     * asked for a unique UMetaSoundSource name, not an ordering fluke. (The four tests run
     * alphabetically, so InputOverrideReachesTheRender is first and is where it fired;
     * RendersNonSilentBuffer never ran.)
     *
     * The fix is the base STRING, not the suffix: two different prefixes can never produce the
     * same full name whatever suffix each branch picks. The serial makes that structural for two
     * fixtures in one process rather than resting on GUID uniqueness, which
     * FPlatformMisc::CreateGuid does not guarantee on every platform.
     */
    FString MakeFixtureId()
    {
        static FThreadSafeCounter Serial;
        return FString::Printf(TEXT("%d_%s"), Serial.Increment(),
            *FGuid::NewGuid().ToString(EGuidFormats::Digits));
    }

    /**
     * Builds the fixture Source, or returns nullptr having recorded why.
     *
     * Every failure here is a HOST condition (no builder subsystem, an unregistered standard
     * node), never a defect in the code under test, which is why the caller reports them as an
     * assertions-skipped marker rather than as a red test.
     */
    UMetaSoundSource* BuildSineSource(FString& OutSkipReason)
    {
        OutSkipReason.Reset();

        // UMetaSoundBuilderSubsystem::Get() arrived in UE 5.4. On 5.3 the only static accessor is
        // GetChecked(), which asserts when the subsystem is absent - the very host condition this
        // fixture reports as a skip - so reach the engine subsystem directly there instead.
#if UE_VERSION_NEWER_THAN_OR_EQUAL(5, 4, 0)
        UMetaSoundBuilderSubsystem* Subsystem = UMetaSoundBuilderSubsystem::Get();
#else
        UMetaSoundBuilderSubsystem* Subsystem =
            GEngine ? GEngine->GetEngineSubsystem<UMetaSoundBuilderSubsystem>() : nullptr;
#endif
        if (!Subsystem)
        {
            OutSkipReason = TEXT("UMetaSoundBuilderSubsystem is not available on this host");
            return nullptr;
        }

        EMetaSoundBuilderResult Result = EMetaSoundBuilderResult::Failed;
        FMetaSoundBuilderNodeOutputHandle OnPlay;
        FMetaSoundBuilderNodeInputHandle OnFinished;
        TArray<FMetaSoundBuilderNodeInputHandle> AudioOuts;

        // Distinct prefixes, one shared id - see MakeFixtureId above for why sharing a base
        // name between these two is a process kill rather than a cosmetic clash.
        const FString FixtureId = MakeFixtureId();
        const FName BuilderName(*FString::Printf(TEXT("PwRenderFixtureBuilder_%s"), *FixtureId));
        const FName SourceName(*FString::Printf(TEXT("PwRenderFixtureSource_%s"), *FixtureId));

        UMetaSoundSourceBuilder* Builder = Subsystem->CreateSourceBuilder(
            BuilderName, OnPlay, OnFinished, AudioOuts, Result,
            EMetaSoundOutputAudioFormat::Mono, /*bIsOneShot=*/false);
        if (!Builder || Result != EMetaSoundBuilderResult::Succeeded || AudioOuts.Num() == 0)
        {
            OutSkipReason = TEXT("CreateSourceBuilder did not produce a Mono source builder");
            return nullptr;
        }

        // UE 5.4 reordered AddNodeByClassName to (ClassName, OutResult, MajorVersion=1) and
        // deprecated the 5.3 (ClassName, MajorVersion, OutResult) spelling.
#if UE_VERSION_NEWER_THAN_OR_EQUAL(5, 4, 0)
        const FMetaSoundNodeHandle SineNode =
            Builder->AddNodeByClassName(SineClassName(), Result, /*MajorVersion=*/1);
#else
        const FMetaSoundNodeHandle SineNode =
            Builder->AddNodeByClassName(SineClassName(), /*MajorVersion=*/1, Result);
#endif
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("the UE.Sine standard node is not registered on this host");
            return nullptr;
        }

        const FMetaSoundBuilderNodeOutputHandle SineAudio =
            Builder->FindNodeOutputByName(SineNode, FName("Audio"), Result);
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("UE.Sine has no 'Audio' output on this engine");
            return nullptr;
        }

        Builder->ConnectNodes(SineAudio, AudioOuts[0], Result);
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("could not connect UE.Sine to the mono audio output");
            return nullptr;
        }

        // The graph input the parameter-override test drives. Reference access (not a
        // constructor input), which is what makes it settable per render.
        FMetasoundFrontendLiteral FrequencyDefault;
        FrequencyDefault.Set(DefaultFrequencyHz);
        const FMetaSoundBuilderNodeOutputHandle FrequencyInput = Builder->AddGraphInputNode(
            FName("Frequency"), FName("Float"), FrequencyDefault, Result,
            /*bIsConstructorInput=*/false);
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("could not add the 'Frequency' graph input");
            return nullptr;
        }

        const FMetaSoundBuilderNodeInputHandle SineFrequency =
            Builder->FindNodeInputByName(SineNode, FName("Frequency"), Result);
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("UE.Sine has no 'Frequency' input on this engine");
            return nullptr;
        }

        Builder->ConnectNodes(FrequencyInput, SineFrequency, Result);
        if (Result != EMetaSoundBuilderResult::Succeeded)
        {
            OutSkipReason = TEXT("could not connect the 'Frequency' graph input to UE.Sine");
            return nullptr;
        }

        FMetaSoundBuilderOptions Options;
        // NOT BuilderName. This is the base name of the UMetaSoundSource that BuildInternal is
        // about to NewObject into /Engine/Transient, where the builder UObject already sits.
        Options.Name = SourceName;
        // bAddToRegistry stays true: the generator resolves the graph through the frontend
        // registry, so a source that is not registered builds to a no-op and renders silence.
#if UE_VERSION_NEWER_THAN_OR_EQUAL(5, 5, 0)
        const TScriptInterface<IMetaSoundDocumentInterface> Built = Builder->Build(Options);
#else
        // The one-argument Build arrived in UE 5.5 and forwards to BuildNewMetaSound, i.e. the
        // null-Parent path of BuildInternal described above. On 5.4 only the two-argument
        // overload exists; passing nullptr for Parent reaches exactly that path.
        const TScriptInterface<IMetaSoundDocumentInterface> Built =
            Builder->Build(/*Parent=*/nullptr, Options);
#endif
        UMetaSoundSource* Source = Cast<UMetaSoundSource>(Built.GetObject());
        if (!Source)
        {
            OutSkipReason = TEXT("the builder produced no UMetaSoundSource");
            return nullptr;
        }

        return Source;
    }

    /** Keeps the transient fixture alive across the render and unregisters it afterwards, so a
     *  later test in the same editor cannot resolve a stale graph out of the frontend registry. */
    struct FScopedFixtureSource
    {
        explicit FScopedFixtureSource(UMetaSoundSource* InSource) : Source(InSource)
        {
            if (Source)
            {
                Source->AddToRoot();
            }
        }

        ~FScopedFixtureSource()
        {
            if (Source)
            {
                Source->UnregisterGraphWithFrontend();
                Source->RemoveFromRoot();
            }
        }

        FScopedFixtureSource(const FScopedFixtureSource&) = delete;
        FScopedFixtureSource& operator=(const FScopedFixtureSource&) = delete;

        UMetaSoundSource* Source = nullptr;
    };

    /** Peak absolute sample across both channels - the cheapest "did anything come out". */
    double MeasurePeak(const FPwAudioBuffer& In)
    {
        double Peak = 0.0;
        for (const float Sample : In.Left)
        {
            Peak = FMath::Max(Peak, FMath::Abs(static_cast<double>(Sample)));
        }
        for (const float Sample : In.Right)
        {
            Peak = FMath::Max(Peak, FMath::Abs(static_cast<double>(Sample)));
        }
        return Peak;
    }
}

// =================================================================================================
// A trivial in-memory MetaSound renders to a non-silent buffer.
// =================================================================================================

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPwMetaSoundRenderNonSilentTest,
    "PinWright.Media.MetaSoundRender.RendersNonSilentBuffer",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FPwMetaSoundRenderNonSilentTest::RunTest(const FString& Parameters)
{
    using namespace PwMetaSoundRenderTestFixture;

    FString SkipReason;
    UMetaSoundSource* Source = BuildSineSource(SkipReason);
    if (!Source)
    {
        PinWrightTestSkip::SkipAssertions(*this, TEXT("metasound-fixture-unbuildable"), SkipReason);
        return true;
    }
    FScopedFixtureSource Scoped(Source);

    FPwMetaSoundRenderParams Params;
    Params.DurationSeconds = 0.25;
    Params.SampleRate = 48000;

    FPwAudioBuffer Buffer;
    FPwMetaSoundRenderReport Report;
    FString Code;
    FString Error;
    const bool bRendered = PwRenderMetaSoundSource(Source, Params, Buffer, Report, Code, Error);

    TestTrue(FString::Printf(TEXT("PwRenderMetaSoundSource succeeds (code='%s', error='%s')"),
        *Code, *Error), bRendered);
    if (!bRendered)
    {
        return false;
    }

    TestTrue(TEXT("the report is marked measured"), Report.bMeasured);
    TestEqual(TEXT("a Mono source resolves to one graph channel"), Report.SourceChannels, 1);
    TestEqual(TEXT("the effective rate matches the requested rate for an asset with no override"),
        Report.EffectiveSampleRate, 48000);
    TestEqual(TEXT("the buffer carries the effective rate"), Buffer.SampleRate,
        Report.EffectiveSampleRate);
    TestEqual(TEXT("0.25 s at 48 kHz is 12000 frames"), Buffer.NumFrames(), 12000);
    TestEqual(TEXT("every requested frame was delivered"), Report.RenderedFrames,
        Report.RequestedFrames);
    TestTrue(TEXT("at least one render callback ran"), Report.BlocksRendered > 0);

    // THE assertion of this test: an oscillator wired to the output produces audio, not zeros.
    // Counterfactual - if the operator were never built (an async build racing the loop, an
    // unregistered graph) OnGenerateAudio would memset and this peak would be exactly 0.
    const double Peak = MeasurePeak(Buffer);
    TestTrue(FString::Printf(TEXT("the render is not silent (peak=%.6f)"), Peak), Peak > 0.05);

    // A non-one-shot source never fires OnFinished, so the duration ceiling is what stopped it.
    TestFalse(TEXT("a non-one-shot source does not report finished"), Report.bFinished);
    TestTrue(TEXT("stopping at the ceiling is reported as truncated"), Report.bTruncated);

    // The shipped analyzer must accept this buffer - that is the whole point of landing the
    // render in the same currency audio.analysis.* speaks.
    FPwAudioAnalysis Analysis;
    FString AnalysisCode;
    FString AnalysisError;
    const bool bAnalyzed = PwAnalyzeBuffer(Buffer, Analysis, AnalysisCode, AnalysisError);
    TestTrue(FString::Printf(TEXT("PwAnalyzeBuffer accepts the render (code='%s')"), *AnalysisCode),
        bAnalyzed);
    if (bAnalyzed)
    {
        TestFalse(TEXT("the analyzer does not call the render digital silence"),
            Analysis.Technical.bDigitalSilence);
        TestEqual(TEXT("the analyzer sees no non-finite samples"),
            Analysis.Technical.NonFiniteSamples, 0);
    }

    return true;
}

// =================================================================================================
// An input override reaches the render.
// =================================================================================================

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPwMetaSoundRenderInputOverrideTest,
    "PinWright.Media.MetaSoundRender.InputOverrideReachesTheRender",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FPwMetaSoundRenderInputOverrideTest::RunTest(const FString& Parameters)
{
    using namespace PwMetaSoundRenderTestFixture;

    FString SkipReason;
    UMetaSoundSource* Source = BuildSineSource(SkipReason);
    if (!Source)
    {
        PinWrightTestSkip::SkipAssertions(*this, TEXT("metasound-fixture-unbuildable"), SkipReason);
        return true;
    }
    FScopedFixtureSource Scoped(Source);

    // Two renders of one asset differing only in the override. Both frequencies are well inside
    // the audible band and a factor of 8 apart, so the measured zero-crossing rate separates them
    // by far more than any estimator tolerance: a sine at f crosses zero 2f times a second.
    const auto RenderAt = [Source](float FrequencyHz, FPwAudioBuffer& OutBuffer,
                                   FPwMetaSoundRenderReport& OutReport, FString& OutCode,
                                   FString& OutError)
    {
        FPwMetaSoundRenderParams Params;
        Params.DurationSeconds = 0.25;
        Params.SampleRate = 48000;
        Params.Inputs.Emplace(FName("Frequency"), FrequencyHz);
        return PwRenderMetaSoundSource(Source, Params, OutBuffer, OutReport, OutCode, OutError);
    };

    FPwAudioBuffer LowBuffer;
    FPwMetaSoundRenderReport LowReport;
    FString LowCode;
    FString LowError;
    const bool bLowRendered = RenderAt(220.0f, LowBuffer, LowReport, LowCode, LowError);
    TestTrue(FString::Printf(TEXT("the 220 Hz render succeeds (code='%s', error='%s')"),
        *LowCode, *LowError), bLowRendered);

    FPwAudioBuffer HighBuffer;
    FPwMetaSoundRenderReport HighReport;
    FString HighCode;
    FString HighError;
    const bool bHighRendered = RenderAt(1760.0f, HighBuffer, HighReport, HighCode, HighError);
    TestTrue(FString::Printf(TEXT("the 1760 Hz render succeeds (code='%s', error='%s')"),
        *HighCode, *HighError), bHighRendered);

    if (!bLowRendered || !bHighRendered)
    {
        return false;
    }

    // The engine drops an override it does not recognise WITHOUT saying so, which is why the
    // report measures the verdict rather than echoing the request.
    TestTrue(TEXT("'Frequency' is reported applied on the 220 Hz render"),
        LowReport.AppliedInputs.Contains(FName("Frequency")));
    TestEqual(TEXT("nothing was rejected on the 220 Hz render"),
        LowReport.RejectedInputs.Num(), 0);
    TestTrue(TEXT("'Frequency' is reported applied on the 1760 Hz render"),
        HighReport.AppliedInputs.Contains(FName("Frequency")));

    // THE assertion of this test. Reporting `applied` only proves the engine ACCEPTED the
    // parameter; this proves the samples changed because of it. Counterfactual - if the override
    // were dropped between InitParameters and the operator build, both renders would carry the
    // graph's 220 Hz default and this ratio would be ~1.
    FPwAudioAnalysis LowAnalysis;
    FPwAudioAnalysis HighAnalysis;
    FString AnalysisCode;
    FString AnalysisError;
    const bool bLowAnalyzed = PwAnalyzeBuffer(LowBuffer, LowAnalysis, AnalysisCode, AnalysisError);
    const bool bHighAnalyzed = PwAnalyzeBuffer(HighBuffer, HighAnalysis, AnalysisCode, AnalysisError);
    TestTrue(TEXT("both renders analyze"), bLowAnalyzed && bHighAnalyzed);
    if (!bLowAnalyzed || !bHighAnalyzed)
    {
        return false;
    }

    const double LowZcr = LowAnalysis.Technical.ZeroCrossingRate;
    const double HighZcr = HighAnalysis.Technical.ZeroCrossingRate;
    TestTrue(FString::Printf(TEXT("the 220 Hz render has a measurable zero-crossing rate (%.1f)"),
        LowZcr), LowZcr > 1.0);
    TestTrue(FString::Printf(
        TEXT("an 8x frequency override raises the zero-crossing rate at least 3x "
             "(220Hz=%.1f, 1760Hz=%.1f)"), LowZcr, HighZcr),
        HighZcr > LowZcr * 3.0);

    return true;
}

// =================================================================================================
// An override the graph has no vertex for is reported, not swallowed.
// =================================================================================================

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPwMetaSoundRenderUnknownInputTest,
    "PinWright.Media.MetaSoundRender.UnknownInputIsReportedRejected",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FPwMetaSoundRenderUnknownInputTest::RunTest(const FString& Parameters)
{
    using namespace PwMetaSoundRenderTestFixture;

    FString SkipReason;
    UMetaSoundSource* Source = BuildSineSource(SkipReason);
    if (!Source)
    {
        PinWrightTestSkip::SkipAssertions(*this, TEXT("metasound-fixture-unbuildable"), SkipReason);
        return true;
    }
    FScopedFixtureSource Scoped(Source);

    FPwMetaSoundRenderParams Params;
    Params.DurationSeconds = 0.1;
    Params.SampleRate = 48000;
    Params.Inputs.Emplace(FName("Frequency"), 440.0f);
    Params.Inputs.Emplace(FName("NoSuchGraphInput"), 1.0f);

    FPwAudioBuffer Buffer;
    FPwMetaSoundRenderReport Report;
    FString Code;
    FString Error;
    const bool bRendered = PwRenderMetaSoundSource(Source, Params, Buffer, Report, Code, Error);
    TestTrue(FString::Printf(TEXT("an unknown override does not fail the render (code='%s')"),
        *Code), bRendered);
    if (!bRendered)
    {
        return false;
    }

    TestTrue(TEXT("the real input is applied"),
        Report.AppliedInputs.Contains(FName("Frequency")));
    // Counterfactual - without the name-set difference the engine's silent RemoveAtSwap would
    // leave the caller unable to tell an override that landed from one that never existed.
    TestTrue(TEXT("the unknown input is reported rejected"),
        Report.RejectedInputs.Contains(FName("NoSuchGraphInput")));
    TestFalse(TEXT("the unknown input is not also reported applied"),
        Report.AppliedInputs.Contains(FName("NoSuchGraphInput")));

    return true;
}

// =================================================================================================
// Range guards. A zero-length render is an error, not an empty success.
// =================================================================================================

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPwMetaSoundRenderRangeGuardTest,
    "PinWright.Media.MetaSoundRender.RejectsOutOfRangeRequests",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::ProductFilter)

bool FPwMetaSoundRenderRangeGuardTest::RunTest(const FString& Parameters)
{
    using namespace PwMetaSoundRenderTestFixture;

    // A null source is a caller bug and must be named as one before anything else runs - no
    // fixture needed, and no engine state touched.
    {
        FPwMetaSoundRenderParams Params;
        FPwAudioBuffer Buffer;
        FPwMetaSoundRenderReport Report;
        FString Code;
        FString Error;
        TestFalse(TEXT("a null source is refused"),
            PwRenderMetaSoundSource(nullptr, Params, Buffer, Report, Code, Error));
        TestEqual(TEXT("a null source reports INVALID_PARAMS"), Code,
            FString(ErrorCodes::ERR_INVALID_PARAMS));
        TestFalse(TEXT("a refused render leaves the report unmeasured"), Report.bMeasured);
        TestFalse(TEXT("a refused render carries a reason"), Error.IsEmpty());
    }

    FString SkipReason;
    UMetaSoundSource* Source = BuildSineSource(SkipReason);
    if (!Source)
    {
        PinWrightTestSkip::SkipAssertions(*this, TEXT("metasound-fixture-unbuildable"), SkipReason);
        return true;
    }
    FScopedFixtureSource Scoped(Source);

    // A zero-length render is an error rather than a zero-frame success: an empty render and a
    // silent one are different outcomes (rpc-design.md section 7).
    {
        FPwMetaSoundRenderParams Params;
        Params.DurationSeconds = 0.0;
        Params.SampleRate = 48000;

        FPwAudioBuffer Buffer;
        FPwMetaSoundRenderReport Report;
        FString Code;
        FString Error;
        TestFalse(TEXT("a zero-length render is refused"),
            PwRenderMetaSoundSource(Source, Params, Buffer, Report, Code, Error));
        TestEqual(TEXT("a zero-length render reports INVALID_PARAMS"), Code,
            FString(ErrorCodes::ERR_INVALID_PARAMS));
        TestEqual(TEXT("a refused render produces no frames"), Buffer.NumFrames(), 0);
    }

    // Above the cap, for the same reason and with the same code.
    {
        FPwMetaSoundRenderParams Params;
        Params.DurationSeconds = PwMetaSoundRenderLimits::MaxDurationSeconds + 1.0;
        Params.SampleRate = 48000;

        FPwAudioBuffer Buffer;
        FPwMetaSoundRenderReport Report;
        FString Code;
        FString Error;
        TestFalse(TEXT("an over-cap duration is refused"),
            PwRenderMetaSoundSource(Source, Params, Buffer, Report, Code, Error));
        TestEqual(TEXT("an over-cap duration reports INVALID_PARAMS"), Code,
            FString(ErrorCodes::ERR_INVALID_PARAMS));
    }

    // A sample rate outside the analyzable window, likewise.
    {
        FPwMetaSoundRenderParams Params;
        Params.DurationSeconds = 0.1;
        Params.SampleRate = PwMetaSoundRenderLimits::MinSampleRate - 1;

        FPwAudioBuffer Buffer;
        FPwMetaSoundRenderReport Report;
        FString Code;
        FString Error;
        TestFalse(TEXT("an under-floor sample rate is refused"),
            PwRenderMetaSoundSource(Source, Params, Buffer, Report, Code, Error));
        TestEqual(TEXT("an under-floor sample rate reports INVALID_PARAMS"), Code,
            FString(ErrorCodes::ERR_INVALID_PARAMS));
    }

    return true;
}

#endif // PW_HAS_METASOUND_RENDER
