// Copyright (c) 2026 Alexander Penkin. MIT License.

// GeometryTransformHandler.cpp - Mirror, linear array, radial array handlers (Phase 18)
#include "Handlers/HandlerRegistration.h"
#include "Handlers/HandlerContext.h"
#include "Handlers/Geometry/GeometryOpCounts.h"
#include "Handlers/Geometry/GeometryOpWarnings.h"
#include "Handlers/Geometry/GeometryOps_Boolean.h"
#include "Handlers/Geometry/GeometryTarget.h"
#include "DynamicMeshActor.h"
#include "Handlers/Geometry/GeometryUtils.h"
#include "Dom/JsonObject.h"


namespace
{
    // Uniquely prefixed: this module builds with bUseUnity = true.
    //
    // The string -> enum mapping stays in the wrapper on purpose (GeometryOps.h): an
    // unrecognized string maps to EMeshAxis::None, which is what preserves each verb's own
    // fallback - neither validates its `axis` param. geometry.mirror then appends an UNMIRRORED
    // clone (doubling the mesh in place) and geometry.array_radial rotates about Z. Mapping it
    // here rather than inside the op is what keeps an unspellable axis out of the op.
    GeometryOps::EMeshAxis GeometryTransformHandler_ParseAxis(const FString& Axis)
    {
        if (Axis == TEXT("X")) return GeometryOps::EMeshAxis::X;
        if (Axis == TEXT("Y")) return GeometryOps::EMeshAxis::Y;
        if (Axis == TEXT("Z")) return GeometryOps::EMeshAxis::Z;
        return GeometryOps::EMeshAxis::None;
    }

    // The post-op vertexCount/triangleCount echo used to live here as a file-name-prefixed copy
    // of MeshOpsHandler.cpp's identical helper, because two anonymous-namespace functions of the
    // same name collide once Unity merges the TUs. It is now the one shared definition in
    // Handlers/Geometry/GeometryOpCounts.h - the named-namespace header CLAUDE.md prescribes for
    // exactly that ODR problem - so the two bodies can no longer drift apart.
}


// ============================================================================
// mirror
// ============================================================================
REGISTER_RPC_HANDLER("geometry.mirror", "geometry", "Mirror a dynamic mesh across a specified axis. Appends the mirrored half into the SAME mesh - it does not replace it and does not spawn an actor. The response carries no vertex/triangle count by design; a mirror the engine could not complete is reported as OPERATION_FAILED rather than as a success.",
    RPC_PARAMS(
        RPC_PARAM_REQ("actorName", "string", "Name of the DynamicMeshActor"),
        RPC_PARAM_OPT("axis", "string", "Mirror axis: X, Y, or Z (default X)"),
        RPC_PARAM_OPT("weld", "boolean", "Weld vertices at mirror plane (default true)"),
        RPC_PARAM_OPT("weldTolerance", "number", "Seam weld tolerance (default 0.001). Deliberately looser than geometry.weld_vertices' 0.0001 and the engine's own 1e-06: mirror welds ONE plane whose two sides it just generated by negating a coordinate, so the only vertices in range are the ones meant to meet, and they miss by whatever floating-point residue the generator left. Tightening it leaves a crack that shows as a lighting split rather than in any count."),
        RPC_PARAM_OPT("onlyUniquePairs", "boolean", "Merge only unambiguous edge pairs during the seam weld (default true)")
    ))
{
    FString ActorName = Ctx.GetString(TEXT("actorName"));
    FString Axis = Ctx.GetString(TEXT("axis"), TEXT("X")).ToUpper();
    bool bWeld = Ctx.GetBool(TEXT("weld"), true);

    FGeometryTarget Target;
    if (!GeometryTarget::ResolveOrSendError(Ctx, ActorName, Target))
        return true;

    GeometryOps::FMirrorParams Params;
    Params.Axis = GeometryTransformHandler_ParseAxis(Axis);
    Params.bWeld = bWeld;
    Params.WeldTolerance = Ctx.GetNumber(TEXT("weldTolerance"), Params.WeldTolerance);
    Params.bOnlyUniquePairs = Ctx.GetBool(TEXT("onlyUniquePairs"), Params.bOnlyUniquePairs);

    // The op's COUNTS are still deliberately dropped: this verb has never echoed a vertex or
    // triangle count, and adding one is a widening this change does not make. The op reports
    // them to the .pwmodel compiler, which does consume them.
    //
    // Its FAILURE is no longer dropped. That used to be justified the same way as the counts -
    // "an observable wire change" - but the two are not the same kind of silence: an unpublished
    // count tells the caller nothing it was promised, whereas a success response for a mesh the
    // engine refused to mirror tells the caller something FALSE, and the caller then builds on
    // geometry that was never produced. Mirror fails with ERR_OPERATION_FAILED when the mirrored
    // half cannot be appended or the seam cannot be welded (GeometryOps_Boolean.cpp). Reporting
    // that as a failure IS an observable change on the failure path, which is the point; the
    // success path is byte-identical, count-less response included.
    //
    // Its WARNINGS are kept, as before: a warning says what the engine did to a value the caller
    // supplied, and discarding the whole result is how those went unseen everywhere in this
    // namespace. Mirror emits none today - capturing the result is what stops the next one from
    // being lost at this boundary.
    const GeometryOps::FOpResult Op = GeometryOps::Mirror(Target.Mesh, Params);

    // Notify BEFORE the failure check, not after it. Mirror's weld-failure path fires after the
    // mirrored half has already been appended, so the mesh really did change even though the op
    // failed; skipping the notify there would leave the component's render proxy showing
    // geometry the mesh no longer has.
    GeometryUtils::MarkGeometryActorModified(Target.Component);

    if (!Op.bSuccess)
    {
        Ctx.SendError(Op.ErrorCode, Op.ErrorMessage);
        return true;
    }

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("actorName"), ActorName);
    GeometryUtils::AddResolvedActorIdentity(Result, Target.Actor);
    Result->SetStringField(TEXT("axis"), Axis);
    GeometryOps::AddOpWarnings(Result, Op);
    Ctx.SendSuccess(TEXT("Mirror applied"), Result);
    return true;
}

// ============================================================================
// array_linear
// ============================================================================
REGISTER_RPC_HANDLER("geometry.array_linear", "geometry", "Merge offset copies of a dynamic mesh into its own geometry (does not spawn new actors)",
    RPC_PARAMS(
        RPC_PARAM_REQ("actorName", "string", "Name of the DynamicMeshActor"),
        RPC_PARAM_OPT("count", "integer", "Total copies including original (default 3); the original counts as 1. The other count-1 copies are merged in place into the source mesh (no new actors)"),
        RPC_PARAM_OPT("offset", "object", "Offset between copies {x, y, z} (default {100,0,0})")
    ))
{
    FString ActorName = Ctx.GetString(TEXT("actorName"));
    int32 Count = Ctx.GetInt(TEXT("count"), 3);
    FVector Offset = GeometryUtils::ReadVectorFromPayload(Ctx.GetRawPayload(), TEXT("offset"), FVector(100, 0, 0));

    if (ActorName.IsEmpty())
    {
        Ctx.SendError(TEXT("INVALID_ARGUMENT"), TEXT("actorName required"));
        return true;
    }

    // Runs before the actor is resolved, as it always has: a bad count together with a missing
    // actor has always reported INVALID_ARGUMENT rather than ACTOR_NOT_FOUND.
    const GeometryOps::FOpResult CountCheck = GeometryOps::ValidateArrayCount(Count);
    if (!CountCheck.bSuccess)
    {
        Ctx.SendError(CountCheck.ErrorCode, CountCheck.ErrorMessage);
        return true;
    }

    FGeometryTarget Target;
    if (!GeometryTarget::ResolveOrSendError(Ctx, ActorName, Target))
        return true;

    GeometryOps::FArrayLinearParams Params;
    Params.Count = Count;
    Params.Offset = Offset;

    // The memory-pressure and polygon-limit guards live inside the op.
    const GeometryOps::FOpResult Op = GeometryOps::ArrayLinear(Target.Mesh, Params);
    if (!Op.bSuccess)
    {
        Ctx.SendError(Op.ErrorCode, Op.ErrorMessage);
        return true;
    }

    GeometryUtils::MarkGeometryActorModified(Target.Component);

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("actorName"), ActorName);
    GeometryUtils::AddResolvedActorIdentity(Result, Target.Actor);
    Result->SetNumberField(TEXT("count"), Count);
    // The array multiplies the source geometry by `count` in place; echo the
    // resulting vertex/triangle counts (matching get_mesh_info's keys) so the
    // caller can confirm the merge landed without a follow-up readback.
    GeometryOps::SetMeshCountFieldsFromOp(Result, Op);
    GeometryOps::AddOpWarnings(Result, Op);
    Ctx.SendSuccess(TEXT("Linear array applied"), Result);
    return true;
}

// ============================================================================
// array_radial
// ============================================================================
REGISTER_RPC_HANDLER("geometry.array_radial", "geometry", "Merge rotated copies of a dynamic mesh into its own geometry around a center (does not spawn new actors)",
    RPC_PARAMS(
        RPC_PARAM_REQ("actorName", "string", "Name of the DynamicMeshActor"),
        RPC_PARAM_OPT("count", "integer", "Total copies including original (default 6); the original counts as 1. The other count-1 copies are merged in place into the source mesh (no new actors)"),
        RPC_PARAM_OPT("center", "object", "Center of rotation {x, y, z} (default origin)"),
        RPC_PARAM_OPT("axis", "string", "Rotation axis: X, Y, or Z (default Z)"),
        RPC_PARAM_OPT("angle", "number", "Total angle in degrees (default 360)")
    ))
{
    FString ActorName = Ctx.GetString(TEXT("actorName"));
    int32 Count = Ctx.GetInt(TEXT("count"), 6);
    FVector Center = GeometryUtils::ReadVectorFromPayload(Ctx.GetRawPayload(), TEXT("center"), FVector::ZeroVector);
    FString Axis = Ctx.GetString(TEXT("axis"), TEXT("Z")).ToUpper();
    double TotalAngle = Ctx.GetNumber(TEXT("angle"), 360.0);

    if (ActorName.IsEmpty())
    {
        Ctx.SendError(TEXT("INVALID_ARGUMENT"), TEXT("actorName required"));
        return true;
    }

    // Runs before the actor is resolved, as it always has: a bad count together with a missing
    // actor has always reported INVALID_ARGUMENT rather than ACTOR_NOT_FOUND.
    const GeometryOps::FOpResult CountCheck = GeometryOps::ValidateArrayCount(Count);
    if (!CountCheck.bSuccess)
    {
        Ctx.SendError(CountCheck.ErrorCode, CountCheck.ErrorMessage);
        return true;
    }

    FGeometryTarget Target;
    if (!GeometryTarget::ResolveOrSendError(Ctx, ActorName, Target))
        return true;

    GeometryOps::FArrayRadialParams Params;
    Params.Count = Count;
    Params.Center = Center;
    Params.Axis = GeometryTransformHandler_ParseAxis(Axis);
    Params.TotalAngleDegrees = TotalAngle;

    // The memory-pressure and polygon-limit guards live inside the op.
    const GeometryOps::FOpResult Op = GeometryOps::ArrayRadial(Target.Mesh, Params);
    if (!Op.bSuccess)
    {
        Ctx.SendError(Op.ErrorCode, Op.ErrorMessage);
        return true;
    }

    GeometryUtils::MarkGeometryActorModified(Target.Component);

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("actorName"), ActorName);
    GeometryUtils::AddResolvedActorIdentity(Result, Target.Actor);
    Result->SetNumberField(TEXT("count"), Count);
    Result->SetNumberField(TEXT("angle"), TotalAngle);
    // The array multiplies the source geometry by `count` in place; echo the
    // resulting vertex/triangle counts (matching get_mesh_info's keys) so the
    // caller can confirm the merge landed without a follow-up readback.
    GeometryOps::SetMeshCountFieldsFromOp(Result, Op);
    GeometryOps::AddOpWarnings(Result, Op);
    Ctx.SendSuccess(TEXT("Radial array applied"), Result);
    return true;
}
